services:
  client:
    command: npm run start:client
    build: .
    env_file:
      - .env
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - frontend
      - zipkin
    networks:
      - otel

  frontend:
    command: npm run start:frontend
    build: .
    ports:
      - 3001:3000
    env_file:
      - .env
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
      - zipkin
    networks:
      - otel

  backend:
    command: npm run start:backend
    build: .
    ports:
      - 3002:3000
    env_file:
      - .env
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - zipkin
    networks:
      - otel

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - otel

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - otel

networks:
  otel:
